version: '3.7' # specify docker-compose version

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
      POSTGRES_USER: user
    volumes:
      - ./data/postgresql:/var/lib/postgresql
# comment the init.sql when using jpa.
#     - ./pg-initdb.d:/docker-entrypoint-initdb.d
      
  mongodb: 
    image: mongo
    restart: always    
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db      
      